const classes = {
    WARRIOR: "Warrior",
    ASSASIN: "Assasin",
    SUPPORT: "Support",
    SPECIALIST: "Specialist",
    MULTICLASS: "Multiclass",
}

const franchises = {
    STARCRAFT: "StarCraft",
    WARCRAFT: "Warcraft",
    DIABLO: "Diablo",
    OVERWATCH: "Overwatch",
} 

module.exports =  [
        { name: "Alarak", class: classes.ASSASIN, francise: franchises.STARCRAFT},
        { name: "Cassia", class: classes.ASSASIN, francise: franchises.DIABLO},
        { name: "Chromie", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Falstad", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Fenix", class: classes.ASSASIN, francise: franchises.STARCRAFT},
        { name: "Greymane", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Gul'dan", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Illidan", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Junkrat", class: classes.ASSASIN, francise: franchises.OVERWATCH},
        { name: "Kael'thas", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Kel'Thuzad", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Kerrigan", class: classes.ASSASIN, francise: franchises.STARCRAFT},
        { name: "Li-Ming", class: classes.ASSASIN, francise: franchises.DIABLO},
        { name: "Lunara", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Malthael", class: classes.ASSASIN, francise: franchises.DIABLO},
        { name: "Ragnaros", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Raynor", class: classes.ASSASIN, francise: franchises.STARCRAFT},
        { name: "Samuro", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "The Butcher", class: classes.ASSASIN, francise: franchises.DIABLO},
        { name: "Thrall", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Tracer", class: classes.ASSASIN, francise: franchises.OVERWATCH},
        { name: "Tychus", class: classes.ASSASIN, francise: franchises.STARCRAFT},
        { name: "Valeera", class: classes.ASSASIN, francise: franchises.WARCRAFT},
        { name: "Varian", class: classes.MULTICLASS, francise: franchises.WARCRAFT},
        { name: "Zeratul", class: classes.ASSASIN, francise: franchises.STARCRAFT},
        { name: "Zul'jin", class: classes.ASSASIN, francise: franchises.WARCRAFT},

        { name: "Anub'arak", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Artanis", class: classes.WARRIOR, francise: franchises.STARCRAFT},
        { name: "Arthas", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Blaze", class: classes.WARRIOR, francise: franchises.STARCRAFT},
        { name: "Chen", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "D.Va", class: classes.WARRIOR, francise: franchises.OVERWATCH},
        { name: "Dehaka", class: classes.WARRIOR, francise: franchises.STARCRAFT},
        { name: "Diablo", class: classes.WARRIOR, francise: franchises.DIABLO},
        { name: "E.T.C.", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Garrosh", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Johanna", class: classes.WARRIOR, francise: franchises.DIABLO},
        { name: "Leoric", class: classes.WARRIOR, francise: franchises.DIABLO},
        { name: "Muradin", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Rexxar", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Sonya", class: classes.WARRIOR, francise: franchises.DIABLO},
        { name: "Stitches", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Tyrael", class: classes.WARRIOR, francise: franchises.WARCRAFT},
        { name: "Zarya", class: classes.WARRIOR, francise: franchises.OVERWATCH},

        { name: "Alexstrasza", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 
        { name: "Ana", class: classes.SUPPORT, francise: franchises.OVERWATCH}, 
        { name: "Brightwing", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 
        { name: "Deckard", class: classes.SUPPORT, francise: franchises.DIABLO}, 
        { name: "Kharazim", class: classes.SUPPORT, francise: franchises.DIABLO}, 
        { name: "Li Li", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 
        { name: "Lt. Morales", class: classes.SUPPORT, francise: franchises.STARCRAFT}, 
        { name: "Lúcio", class: classes.SUPPORT, francise: franchises.OVERWATCH}, 
        { name: "Malfurion", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 
        { name: "Rehgar", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 
        { name: "Stukov", class: classes.SUPPORT, francise: franchises.STARCRAFT}, 
        { name: "Tassadar", class: classes.SUPPORT, francise: franchises.STARCRAFT}, 
        { name: "Tyrande", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 
        { name: "Uther", class: classes.SUPPORT, francise: franchises.WARCRAFT}, 

        { name: "Azmodan", class: classes.SPECIALIST, francise: franchises.DIABLO}, 
        { name: "Gazlowe", class: classes.SPECIALIST, francise: franchises.WARCRAFT}, 
        { name: "Medivh", class: classes.SPECIALIST, francise: franchises.WARCRAFT}, 
        { name: "Murky", class: classes.SPECIALIST, francise: franchises.WARCRAFT}, 
        { name: "Nazeebo", class: classes.SPECIALIST, francise: franchises.DIABLO}, 
        { name: "Probius", class: classes.SPECIALIST, francise: franchises.STARCRAFT}, 
        { name: "Sgt. Hammer", class: classes.SPECIALIST, francise: franchises.STARCRAFT}, 
        { name: "Sylvanas", class: classes.SPECIALIST, francise: franchises.WARCRAFT}, 
        { name: "Xul", class: classes.SPECIALIST, francise: franchises.DIABLO}, 
        { name: "Zagara", class: classes.SPECIALIST, francise: franchises.STARCRAFT}, 
    ]    



    